/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Model;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author JayJomJohn
 */
public class Form_AddNewStudent extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    CallableStatement cst;

    private String imagePath, gender, combination;

    public Form_AddNewStudent() {
        initComponents();
        conn = Database.JavaConnector.ConnectDB();
        showReset();
        showIcon();
        showFrame();

    }

    private void showFrame() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    private void ComputingAge() {
        try {
            String monthValue = (String) cmbboxMonth.getSelectedItem();
            String dayValue = (String) cmbboxDay.getSelectedItem();
            String yearValue = txtYear.getText();
            String converting = monthValue;
            switch (converting) {
                case ("January"):
                    converting = "01";
                    break;
                case ("February"):
                    converting = "02";
                    break;
                case ("March"):
                    converting = "03";
                    break;
                case ("April"):
                    converting = "04";
                    break;
                case ("May"):
                    converting = "05";
                    break;
                case ("June"):
                    converting = "06";
                    break;
                case ("July"):
                    converting = "07";
                    break;
                case ("August"):
                    converting = "08";
                    break;
                case ("September"):
                    converting = "09";
                    break;
                case ("October"):
                    converting = "10";
                    break;
                case ("November"):
                    converting = "11";
                    break;
                case ("December"):
                    converting = "12";
                    break;
            }
            int day = Integer.parseInt(dayValue);
            int month = Integer.parseInt(converting);
            int year = Integer.parseInt(yearValue);
            LocalDate selectedDate = LocalDate.of(year, month, day);
            LocalDate currentDate = LocalDate.now();
            int resultYear = Period.between(selectedDate, currentDate).getYears();
            txtAge.setText("" + resultYear);
        } catch (NumberFormatException ex) {
            System.out.println(ex);
        }
    }

    private void showReset() {
        txtLastName.setText("");
        txtAddress.setText("");
        txtFirstName.setText("");
        txtMiddleName.setText("");
        txtAge.setText("");
        txtAddress.setText("");
        radiobtnMale.setSelected(false);
        radiobtnFemale.setSelected(false);
        cmbboxMonth.setSelectedItem("Month");
        cmbboxDay.setSelectedItem("Day");
        txtYear.setText("Year");
        ImageIcon myimage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/BLANKPICTURE.png")));
        Image img1 = myimage.getImage();
        Image img2 = img1.getScaledInstance(lblProfile.getWidth(), lblProfile.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        lblProfile.setIcon(i);
        imagePath = null;

    }

    private void showIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/job.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblLastName = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblLastName1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName2 = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        lblLastName3 = new javax.swing.JLabel();
        radiobtnFemale = new javax.swing.JRadioButton();
        radiobtnMale = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        cmbboxMonth = new javax.swing.JComboBox<>();
        cmbboxDay = new javax.swing.JComboBox<>();
        txtYear = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblLastName5 = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JTextField();
        lblLastName6 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblLastName7 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnTakeAPicture = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD NEW STUDENT");
        setMaximumSize(new java.awt.Dimension(1300, 450));
        setMinimumSize(new java.awt.Dimension(1300, 450));
        setPreferredSize(new java.awt.Dimension(1300, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 450));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName.setText("AGE:");
        jPanel2.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 50, 30));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 800, 30));

        lblLastName1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName1.setText("FIRST NAME:");
        jPanel2.add(lblLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 120, 30));

        txtFirstName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });
        jPanel2.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 185, 30));

        lblLastName2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName2.setText("MIDDLE NAME:");
        jPanel2.add(lblLastName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 140, 30));

        lblProfile.setBackground(new java.awt.Color(34, 167, 240));
        lblProfile.setOpaque(true);
        jPanel2.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 231, 174));

        lblLastName3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName3.setText("LAST NAME:");
        jPanel2.add(lblLastName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 30));

        buttonGroup1.add(radiobtnFemale);
        radiobtnFemale.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radiobtnFemale.setText("FEMALE");
        radiobtnFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radiobtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnFemaleActionPerformed(evt);
            }
        });
        jPanel2.add(radiobtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 120, 110, 30));

        buttonGroup1.add(radiobtnMale);
        radiobtnMale.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radiobtnMale.setText("MALE");
        radiobtnMale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radiobtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobtnMaleActionPerformed(evt);
            }
        });
        jPanel2.add(radiobtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, 30));

        btnBack.setBackground(new java.awt.Color(219, 10, 91));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setDefaultCapable(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 170, 40));

        btnAdd.setBackground(new java.awt.Color(30, 139, 195));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("ADD");
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 170, 40));

        cmbboxMonth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbboxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cmbboxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxMonthActionPerformed(evt);
            }
        });
        jPanel2.add(cmbboxMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 131, 30));

        cmbboxDay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbboxDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbboxDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbboxDayActionPerformed(evt);
            }
        });
        jPanel2.add(cmbboxDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 71, 30));

        txtYear.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYearFocusLost(evt);
            }
        });
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYearKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });
        jPanel2.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, 93, 30));

        txtAge.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });
        jPanel2.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 60, 30));

        lblLastName5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName5.setText("DATE OF BIRTH:");
        jPanel2.add(lblLastName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 150, 30));

        txtMiddleName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMiddleName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMiddleNameKeyTyped(evt);
            }
        });
        jPanel2.add(txtMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 70, 70, 30));

        lblLastName6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName6.setText("GENDER:");
        jPanel2.add(lblLastName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 30));

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });
        jPanel2.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 185, 30));

        lblLastName7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLastName7.setText("ADDRESS:");
        jPanel2.add(lblLastName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, 30));

        btnBrowse.setBackground(new java.awt.Color(0, 51, 102));
        btnBrowse.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBrowse.setForeground(java.awt.Color.white);
        btnBrowse.setText("BROWSE");
        btnBrowse.setBorderPainted(false);
        btnBrowse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBrowse.setFocusable(false);
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        jPanel2.add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 103, 30));

        btnTakeAPicture.setBackground(new java.awt.Color(102, 0, 102));
        btnTakeAPicture.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTakeAPicture.setForeground(java.awt.Color.white);
        btnTakeAPicture.setText("TAKE A PICTURE");
        btnTakeAPicture.setBorderPainted(false);
        btnTakeAPicture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTakeAPicture.setFocusable(false);
        btnTakeAPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakeAPictureActionPerformed(evt);
            }
        });
        jPanel2.add(btnTakeAPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 220, 118, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1280, 428));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (btnBack.getText().equals("BACK")) {
            this.hide();
            Form_Student nextForm = new Form_Student();
            nextForm.show();
        } else {
            try {
                int P = JOptionPane.showConfirmDialog(null, " Are you sure want to cancel ?", "ATTENTION", JOptionPane.YES_NO_OPTION);
                if (P == JOptionPane.YES_OPTION) //(P==0) //YES FOR 0 NO FOR 1
                {
                    this.hide();
                    Form_Student nextForm = new Form_Student();
                    nextForm.show();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    public ImageIcon ResizeImage(String imagePath, byte[] pic) {
        ImageIcon myImage = null;
        if (imagePath != null) {
            myImage = new ImageIcon(imagePath);
        } else {
            myImage = new ImageIcon(pic);
        }
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lblProfile.getWidth(), lblProfile.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private void btnBrowseClicked() {
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.image", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lblProfile.setIcon(ResizeImage(path, null));
            imagePath = path;
        } else {
            System.out.println("No File Selected");
        }
    }

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        btnBrowseClicked();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnTakeAPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeAPictureActionPerformed
        Form_Camera nextForm = new Form_Camera();
        nextForm.setVisible(true);
        nextForm.setLocationRelativeTo(this);
        nextForm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                hide();
            }
        });
    }//GEN-LAST:event_btnTakeAPictureActionPerformed

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        if (!txtAddress.getText().equals("")) {
            btnBack.setText("CANCEL");
        } else {
            btnBack.setText("BACK");
        }
    }//GEN-LAST:event_txtLastNameKeyReleased

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        if (txtAddress.getText().length() >= 16) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        if (txtFirstName.getText().length() >= 16) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtMiddleNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMiddleNameKeyTyped
        if (txtMiddleName.getText().length() >= 16) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMiddleNameKeyTyped

    private void cmbboxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxMonthActionPerformed
        ComputingAge();
    }//GEN-LAST:event_cmbboxMonthActionPerformed

    private void cmbboxDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbboxDayActionPerformed
        ComputingAge();
    }//GEN-LAST:event_cmbboxDayActionPerformed

    private void txtYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusGained
        if (txtYear.getText().equals("Year")) {
            txtYear.setText("");
        }
    }//GEN-LAST:event_txtYearFocusGained

    private void txtYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusLost
        if (txtYear.getText().equals("")) {
            txtYear.setText("Year");
            txtAge.setText("");
        }
    }//GEN-LAST:event_txtYearFocusLost

    private void txtYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyReleased
        if (this.txtYear.getText().equals("")) {
            txtAge.setText("");
        } else {
            ComputingAge();
        }
    }//GEN-LAST:event_txtYearKeyReleased

    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtYear.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtYearKeyTyped

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        if (txtAge.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_txtAgeKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtLastName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Last Name Found!", "ATTENTIOM", JOptionPane.ERROR_MESSAGE);
            txtLastName.requestFocus();

        } else if (txtFirstName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Given Name Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtFirstName.requestFocus();

        } else if (txtMiddleName.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Middle Name Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtMiddleName.requestFocus();

        } else if (radiobtnMale.isSelected() == false && radiobtnFemale.isSelected() == false) {
            JOptionPane.showMessageDialog(this, "No Gender Found!", "ATTENTIOM", JOptionPane.ERROR_MESSAGE);

        } else if (cmbboxMonth.getSelectedItem().equals("Month")) {
            JOptionPane.showMessageDialog(this, "No Month Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            cmbboxMonth.requestFocus();

        } else if (cmbboxDay.getSelectedItem().equals("Day")) {
            JOptionPane.showMessageDialog(this, "No Day Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            cmbboxDay.requestFocus();

        } else if (txtYear.getText().equals("Year")) {
            JOptionPane.showMessageDialog(this, "No Year Found!", "ATTENTIOM", JOptionPane.ERROR_MESSAGE);
            txtYear.requestFocus();

        } else if (txtAge.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Age Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtAge.requestFocus();

        } else if (txtAddress.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No Address Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
            txtAddress.requestFocus();

        } else {

            try {
                String month = (String) cmbboxMonth.getSelectedItem();
                String day = cmbboxDay.getSelectedItem().toString();
                String year = txtYear.getText();
                combination = year + "-" + month + "-" + day;
                if (imagePath != null) {
                    DateFormat pattern = new SimpleDateFormat("yyyy-MMMM-dd");
                    Date myDate = pattern.parse(combination);
                    java.sql.Date converted = new java.sql.Date(myDate.getTime());
                    cst = conn.prepareCall("{call sp_InsertNewStudent(?, ?, ?, ?, ?, ?, ?, ?)}");
                    cst.setString(1, txtLastName.getText());
                    cst.setString(2, txtFirstName.getText());
                    cst.setString(3, txtMiddleName.getText());
                    cst.setString(4, gender);
                    cst.setDate(5, converted);
                    cst.setString(6, txtAge.getText());
                    cst.setString(7, txtAddress.getText());
                    InputStream inputStream = new FileInputStream(new File(imagePath));
                    cst.setBlob(8, inputStream);

                    if (cst.executeUpdate() == 1) {
                        JOptionPane.showMessageDialog(this, "Successfully Added!", "ATTENTION", JOptionPane.INFORMATION_MESSAGE);
                       
                        showReset();
                        btnAdd.setEnabled(false);
                        btnBack.setText("BACK");
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "No Photo Found!", "ATTENTION", JOptionPane.ERROR_MESSAGE);
                    btnBrowseClicked();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void radiobtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnMaleActionPerformed
        gender = "1";
        if (radiobtnMale.isSelected() == true) {
            radiobtnFemale.setSelected(false);
        }
    }//GEN-LAST:event_radiobtnMaleActionPerformed

    private void radiobtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobtnFemaleActionPerformed
        gender = "2";
        if (radiobtnFemale.isSelected() == true) {
            radiobtnMale.setSelected(false);
        }
    }//GEN-LAST:event_radiobtnFemaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_AddNewStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_AddNewStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnTakeAPicture;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbboxDay;
    private javax.swing.JComboBox<String> cmbboxMonth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblLastName2;
    private javax.swing.JLabel lblLastName3;
    private javax.swing.JLabel lblLastName5;
    private javax.swing.JLabel lblLastName6;
    private javax.swing.JLabel lblLastName7;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JRadioButton radiobtnFemale;
    private javax.swing.JRadioButton radiobtnMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
